### ISSUE TITLE
Allow installing extra packages for the GitHub Action

### ISSUE THREAD

**Issue by akaihola** [akaihola/graylint#1]
Sometimes linters can use or require other packages than the linter itself. Some such examples are:
- `flake8` plugins
- `mypy` following imports and checking type hints against typing of imported packages

In such situations, the action needs to be able to install those additional packages.

For this feature, an additional option is needed. An example:
```yaml
     - uses: akaihola/graylint@0.0.1
       with:
         src: "./mypackage"
         revision: "origin/main..."
         lint: "flake8,mypy"
         extra_packages: "-e .[test] flake8-docstrings"
```

The value of `extra_packages` should be appended to the `pip install` command line as such.

### Alternatives
- The option for installing the tested package (and possibly extras like `[test]`) could be separated to another option for clarity.
